databases:
  - name: django_render_db
    plan: free
    databaseName: django_render_db
    user: django_user
    region: singapore

services:
  - type: web
    name: BisinessHakase
    plan: free
    env: python
    region: singapore
    branch: main
    healthCheckPath: /api/
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_render_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
    autoDeploy: true
