# Generated by Django 3.1.14 on 2023-05-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='booktitle',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='main',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.TextField(max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='word',
            field=models.ManyToManyField(blank=True, related_name='word', to='api.Dictionary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchWord',
            field=models.ManyToManyField(blank=True, related_name='searchWord', to='api.Dictionary'),
        ),
    ]
