# Generated by Django 3.1.14 on 2023-05-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230507_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='searchWord',
        ),
        migrations.CreateModel(
            name='SearchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.ManyToManyField(blank=True, related_name='searchText', to='api.Dictionary')),
                ('user', models.ManyToManyField(blank=True, related_name='searchUser', to='api.Profile')),
            ],
        ),
    ]
