# Generated by Django 3.1.14 on 2023-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230507_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchinfo',
            name='created_on',
        ),
        migrations.AddField(
            model_name='searchinfo',
            name='searched_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
